import bcrypt from "bcryptjs";

const data = {
  // users: [
  //   {
  //     firstName: "Tunji",
  //     lastName: "Akande",
  //     email: "shopmate400@gmail.com",
  //     password: bcrypt.hashSync("Akande95"),
  //     isAdmin: true,
  //     isBlocked: false,
  //     isSeller: false,
  //     isAccountVerified: false,
  //   },
  //   {
  //     firstName: "John",
  //     lastName: "Stew",
  //     email: "user@example.com",
  //     password: bcrypt.hashSync("123456"),
  //     isAdmin: false,
  //     isBlocked: false,
  //     isSeller: false,
  //     isAccountVerified: false,
  //   },
  // ],
  products: [
    {
      name: "Bracelet Armchair Fendi",
      slug: "Bracelet Armchair Fendi Casa",
      keygen: "SKU BK3569",
      gender: [],
      category: ["office chair", "Round Table"],
      size: ["32 Fit by 14 Fit"],
      color: [
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1686772607/pxdsmlnqamgzmphioqpg.png",
      ],
      price: 20,
      countInStock: 20,
      numSales: 0,
      discount: 10,
      brand: ["Office Chair"],
      image:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1686571535/ccnuzt8ieikazohiog9w.jpg",
      images: [
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1686747981/hqfxo8djjwtpaployoiq.png",
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1686748391/blni9nkafaoslvpwhwxp.png",
      ],
      desc: '<table style="border-collapse:collapse;width: 100%;"><tbody>\n<tr>\n\t<td style="width: 35.5051%;">HEIGHT</td><td style="width: 47.0588%;">Inches(34.6)</td><td style="width: 17.3375%;">CM(88)</td></tr>\n<tr>\n\t<td style="width: 41.1765%;">WIDTH</td><td style="width: 41.1765%;">Inches(17.7 x 89.4)</td><td style="width: 49.9226%;">CM(182 x227)</td></tr></tbody></table><p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit.Consectetur neque, quidem harum tempore, laboriosam modi magnisapiente, illum pariatur dolorum nemo! Magnam quaerat ducimus,delectus vero ipsum facere quis ipsam fuga? Obcaecati odioporro, eveniet, ipsum quidem dolorum doloremque ea mollitiaaliquid nulla error temporibus eaque beatae soluta modiconsequatur tempore voluptatibus earum rerum facere,praesentium deserunt tenetur expedita. Ducimus.<br></span><br></p>',
      rating: 5,
      numReviews: 1,
      reviews: [],
      createdAt: "2023-06-12T12:09:23.258Z",
      updatedAt: "2023-06-18T16:39:21.842Z",
      __v: 8,
      flashdeal: true,
    },
    {
      name: "Single Sofa Chair",
      slug: "Single Sofa Chair",
      keygen: "",
      category: ["Dinning Table"],
      size: [],
      color: [],
      price: 600,
      countInStock: 20,
      numSales: 0,
      discount: null,
      brand: [],
      image:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1687022292/pmcdkr4ehjcq5azmksqs.jpg",
      images: [],
      desc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.</p>",
      rating: 2.5,
      numReviews: 1,
      reviews: [],
      createdAt: "2023-06-17T17:20:21.196Z",
      updatedAt: "2023-06-18T16:42:10.480Z",
      __v: 1,
      flashdeal: true,
    },
    {
      name: "Chair without arm",
      slug: "Chair without arm",
      keygen: "",
      category: ["Dinning Table"],
      size: [],
      color: [],
      price: 500,
      countInStock: 20,
      numSales: 0,
      discount: null,
      brand: [],
      images: [],
      desc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.</p>",
      rating: 0,
      numReviews: 0,
      reviews: [],
      createdAt: "2023-06-17T17:22:15.197Z",
      updatedAt: "2023-06-18T16:42:27.781Z",
      __v: 0,
      image:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1687024076/d0inm4xhgvlayccbltpi.jpg",
      flashdeal: true,
    },
    {
      flashdeal: false,

      name: "Chair",
      slug: "Chair",
      keygen: "SKU BK3569",
      category: ["Table"],
      size: [],
      color: [],
      price: 700,
      countInStock: 10,
      numSales: 0,
      discount: 50,
      brand: [],
      image:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1687076443/yycsxuxjmn3q7cackkh0.jpg",
      images: [],
      desc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.</p>",
      rating: 0,
      numReviews: 0,
      reviews: [],
      createdAt: "2023-06-18T08:21:24.221Z",
      updatedAt: "2023-06-18T08:21:24.221Z",
      __v: 0,
    },
    {
      flashdeal: false,
      name: "Chair Table",
      slug: "Chair",
      keygen: "SKU BK3569",
      category: ["Round Table"],
      size: [],
      color: [],
      price: 500,
      countInStock: 10,
      numSales: 0,
      discount: 60,
      brand: [],
      image:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1687076580/jrr8vyue9hdohp8jnlt4.jpg",
      images: [],
      desc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.</p>",
      rating: 0,
      numReviews: 0,
      reviews: [],
      createdAt: "2023-06-18T08:23:30.170Z",
      updatedAt: "2023-06-18T08:23:30.170Z",
      __v: 0,
    },
    {
      flashdeal: false,
      name: "Chair with arm",
      slug: "Chair with arm",
      keygen: "SKU BK3569",
      category: ["Table"],
      size: [],
      color: [],
      price: 800,
      countInStock: 10,
      numSales: 0,
      discount: 55,
      brand: [],
      image:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1687076737/ptux77nwgz2gn3y3kpoc.jpg",
      images: [],
      desc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.</p>",
      rating: 0,
      numReviews: 0,
      reviews: [],
      createdAt: "2023-06-18T08:25:43.975Z",
      updatedAt: "2023-06-18T08:25:43.975Z",
      __v: 0,
    },
    {
      flashdeal: false,
      name: "Chair without arms",
      slug: "Chair without arms",
      keygen: "SKU BK3569",
      category: ["Table"],
      size: [],
      color: [],
      price: 1000,
      countInStock: 10,
      numSales: 0,
      discount: 65,
      brand: [],
      image:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1687076863/ib2cxbblmhyyz7efqngu.jpg",
      images: [],
      desc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.</p>",
      rating: 0,
      numReviews: 0,
      reviews: [],
      createdAt: "2023-06-18T08:28:03.183Z",
      updatedAt: "2023-06-18T08:28:03.183Z",
      __v: 0,
    },
    {
      flashdeal: false,
      name: "Sataclable Arm Chair",
      slug: "Sataclable Arm Chair",
      keygen: "SKU BK3569",
      category: ["Dinning Table"],
      size: [],
      color: [],
      price: 750,
      countInStock: 10,
      numSales: 0,
      discount: 75,
      brand: [],
      image:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1687076988/f84iimyj5e3k4dzdfuyj.jpg",
      images: [],
      desc: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.</p>",
      rating: 0,
      numReviews: 0,
      reviews: [],
      createdAt: "2023-06-18T08:30:04.206Z",
      updatedAt: "2023-06-18T08:30:04.206Z",
      __v: 0,
    },
  ],
  settings: [
    {
      about: "Your About here",
      terms: "Your terms here",
      returns: "Your return here",
      privacy: "Your privacy here",
      currency: "GBP",
      currencySign: "£",
      tax: 14,
      shipping: 24,
      express: "Your express here",
      expressCharges: "Your express here",
      standard: "Your standard here",
      standardCharges: "Your standard charges here",
      facebook: "https://web.facebook.com/",
      twitter: "https://twitter.com/",
      youtube: "https://youtube.com/",
      instagram: "https://www.instagram.com/",
      pinterest: "https://www.pinterest.com/",
      webname: "SHOPMATE",
      bannerBackground:
        "https://res.cloudinary.com/dstj5eqcd/image/upload/v1673724164/banner2_l71yuh.png",
      sizeGuide: "size guidelines",
      reviewGuide: "review guidelines",
      navOne: "Women",
      navTwo: "Men",
      navThree: "Kids",
      navFour: "Shoes",
      navFive: "Brand",
    },
  ],
};

export default data;
