import couch1 from "../../../assets/ProCanes/1.jpg"
const StoreData = {
  shopItems: [
    {
      id: 7,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "180",
      discount: "25",
    },
    {
      id: 8,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "120",
      discount: "10",
    },
    {
      id: 9,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "20",
      discount: "50 ",
    },
    {
      id: 10,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "999",
      discount: "10 ",
    },
    {
      id: 11,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "80",
      discount: "20 ",
    },
    {
      id: 12,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "400",
      discount: "20 ",
    },
    {
      id: 13,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "60",
      discount: "5 ",
    },
    {
      id: 14,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "120",
      discount: "10",
    },
    {
      id: 15,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "5",
      discount: "2",
    },
    {
      id: 8,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "120",
      discount: "10",
    },
    {
      id: 9,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "20",
      discount: "50 ",
    },
    {
      id: 10,
      cover: couch1,
      name: "Bracelet Armchair Fendi Casa",
      price: "999",
      discount: "10 ",
    },
  ],
};
export default StoreData;
